### ISSUE TITLE
Plug-in causes benches and bins to appear on paths outside owned land

### ISSUE THREAD

**Issue by Fred-1044276** [tubbo/openrct2-benchwarmer#1]
This plugin is great for quickly putting benches and bins in the park, but there is an issue that has yet to be fixed: this plugin actually causes benches and bins to appear on paths that are in land not owned by park, even if the sandbox mode cheat is already off.

**Comment by tubbo** [comment]
Hey @Fred-1044276, thanks for letting me know! This would definitely cause an issue since those additional paths/bins would deduct also deduct your cash when they don't need to. Definitely shouldn't be building on paths you don't own.

Looking through the [available JS interfaces](https://github.com/OpenRCT2/OpenRCT2/blob/develop/distribution/openrct2.d.ts), I don't see an obvious way to know whether a tile is owned by the park or not. That said, there seems to be a `.data` property inside the tile that I can see if maybe has the information we need.
