### ISSUE TITLE
Suggestion: Add Bin/Bench while placing paths.

### ISSUE THREAD

**Issue by RundesBalli** [tubbo/openrct2-benchwarmer#14]
Currently, you have to use the `Map-Menu` => `Benchwarmer` => `Add-Button` to place Bins and Benches.

It would be very nice, if B&B's would placed automatically while placing paths. I don't know, if the API has a "trigger" for this "placing-event". If not, then this could be done via the `interval.day`-"Event" like in this plugin from @RGBrewer:
https://github.com/RGBrewer/OpenRCT2-Mow-Grass/blob/master/mow_grass_daily.js#L13-L15

Sorry, I don't know JavaScript and I don't know the correct terms. I hope you understand my suggestion.

**Comment by tubbo** [comment]
This would be great, but I'm not sure if OpenRCT's APIs will allow for it. There's actually no documentation for any of this (yet), I'm reading the TypeScript definitions to get an idea of what APIs are made available to me. OpenRCT has a concept of "subscriptions" in which you can subscribe to various events that occur in the game, so this might be technically possible. [Here's a list of them](https://github.com/OpenRCT2/OpenRCT2/blob/develop/distribution/openrct2.d.ts#L219-L228).

I would assume that the `action.execute` event is most likely the one that Benchwarmer would want to subscribe to in order to receive information about when paths were placed. It could listen to this event and whenever a path was placed, the plugin could add a bench or bin to that path depending on what was selected in the UI.

**Comment by RundesBalli** [comment]
> but I'm not sure if OpenRCT's APIs will allow for it.
That's why I linked the other project with the daily subscription. In my opinion is the daily execution of the script absolutely sufficient. In this case there is no need to study the API documentation again or find out which api endpoints are responsible for that.

Reading English is so much easier than writing it :-D Sorry if anything makes no sense.

**Comment by tubbo** [comment]
That wouldn't be sufficient in my opinion. You can build paths faster than a single day can pass, and it would be really strange to build paths and then out of nowhere bins/benches just get placed on them at some point in the future, depending on how fast you're running the game. Also this code would be running every (game) day regardless of whether you need it or not, which is going to add more lag to your game. I would much rather subscribe to a more relevant event and sense whether something was built.

**Comment by RundesBalli** [comment]
I don't had this in my mind. You are right.
I was just brainstorming :-)

**Comment by tubbo** [comment]
It seems that OpenRCT2 now has an [action.execute](https://github.com/OpenRCT2/OpenRCT2/blob/master/distribution/openrct2.d.ts#L224) subscription that we can listen on. This should be able to tell us whenever a footpath has been placed, and we can add bench/bin additions "as you go".

To get this actually working, a number of changes will need to be made, especially to the UI of this plugin:

1. The normal workflow for adding bins/benches will change from "build when I click OK" to "build all the time".
2. The dialog will have to retain its settings (#17), because we'll need to know what bench/bin you selected as new footpaths are being constructed.
3. The "OK" button will be renamed to "Build on All Paths", which will cause bins/benches to be placed everywhere

I think this will warrant a major version (breaking change) upgrade, now that we know how it can be done. In that major version, I'd also like to implement @ZehMatt's suggestion of [using game actions](https://github.com/OpenRCT2/OpenRCT2/issues/12995#issuecomment-698828959) rather than manipulating data points directly. I believe if we go this route, we'll be able to remove a lot of the ad-hoc "validation" code that exists in this plugin, such as making sure you have enough cash, making sure footpaths are within construction boundaries, etc.

**Comment by tubbo** [comment]
@RundesBalli here's a build for this feature too

[benchwarmer.js.zip](https://github.com/tubbo/openrct2-benchwarmer/files/8126532/benchwarmer.js.zip)

**Comment by tubbo** [comment]
@RundesBalli I made a build for this feature as well if you want to check it out.
[benchwarmer.js.zip](https://github.com/tubbo/openrct2-benchwarmer/files/8126590/benchwarmer.js.zip)

**Comment by RundesBalli** [comment]
Of course, thank you!

![grafik](https://user-images.githubusercontent.com/46271553/155408075-c5b54ae1-2ba0-41d1-aa50-ec651295f5dd.png)

Works as intended!

The financial overview (as in #20) updates as well in realtime!

**Comment by RundesBalli** [comment]
I've found a bug:

Lets assume this scenario:
![grafik](https://user-images.githubusercontent.com/46271553/155409752-fc40db10-3fa9-4d84-884d-362030cf8b7b.png)

When you place a path in the center of the brown paths, it throws an error, because it is - of course - not possible to place benches/bins anywhere in there:
![grafik](https://user-images.githubusercontent.com/46271553/155409861-824f1edd-9f22-4064-95a4-bfb155a546b6.png)

Other Scenario:
![grafik](https://user-images.githubusercontent.com/46271553/155409682-67500ad1-4c1c-42a5-9f0b-9034cce67e23.png)

**Comment by RundesBalli** [comment]
Found another one!
While placing queue:
![grafik](https://user-images.githubusercontent.com/46271553/155598284-001f8804-b0cf-4811-a9bc-bdecaf3800fe.png)

**Comment by RundesBalli** [comment]
Another comment:
When building pre planned coasters from the templates that include scenario elements, benches/bins are not automatically added to the path.

**Comment by tubbo** [comment]
> When building pre planned coasters from the templates that include scenario elements, benches/bins are not automatically added to the path.

I don't think the game considers prebuilds to be "executing the action" of placing a footpath. It's like an all-or-nothing thing, which is supported by the fact that you get a flat price deducted from your financial total. So I don't think prebuilds will include this feature. I can make a comment in the README that makes this more clear, but yeah I don't think I can/should touch prebuilds.

**Comment by tubbo** [comment]
> Maybe the game provides a "I've just built a prebuild-coaster"-action 

Unfortunately, it does not, so far as I've seen.

**Comment by RundesBalli** [comment]
> @RundesBalli
> 
> > Maybe the game provides a "I've just built a prebuild-coaster"-action
> 
> Unfortunately, it does not, so far as I've seen.

Maybe the game could execute the "place on all paths" function every 10 days? Or once a month?
