### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by nepumax** [tubbo/openrct2-benchwarmer#2]
I've been waiting for this mod for along time, but it doesn't work!

When I open the menu, pick the bench and the bin and click "Add" it just freezes for a second and nothing happens.

![Forest Frontiers 2020-08-19 23-48-33](https://user-images.githubusercontent.com/2079937/90693088-82669280-e276-11ea-9aca-145645883503.png)
![Forest Frontiers 2020-08-19 23-48-46](https://user-images.githubusercontent.com/2079937/90693085-81356580-e276-11ea-98be-d695e365d855.png)

I'm using version 0.3.0-20-g8d141fa on develop.

**Comment by tubbo** [comment]
Interesting. Works for me on the tagged [v0.3.0](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.3.0) release made 5 days ago, maybe try that instead of a Git branch? Typically the `develop` branch is a moving target, and might contain code that breaks the JS APIs I'm using here in the plugin.

**Comment by tubbo** [comment]
The plugin works on the macOS build of [the latest commit](https://github.com/OpenRCT2/OpenRCT2/actions/runs/216207576), try using that build for your platform?

**Comment by nepumax** [comment]
I'm using the launcher on Windows 10 64-bit.

I did further research and found out, that it doesn't work on RCT1 maps.
On RCT2 maps it just works with a specific choice of benches.

When I choose _Bench rct2.bench1_ it does not work with _Litter Bin rct2.litter1_, _Litter Bin rct2.littermm_,  _Litter Bin rct2.litterww_.
If I pick _Bench rct2.benchlog_, it works with every litter bin.

![Crazy Castle 2020-08-20 14-34-35](https://user-images.githubusercontent.com/2079937/90770922-cf884a00-e2f2-11ea-81dc-811295453894.png)
![Crazy Castle 2020-08-20 14-35-59](https://user-images.githubusercontent.com/2079937/90770921-ceefb380-e2f2-11ea-840d-ce70dfb164d9.png)
![Crazy Castle 2020-08-20 14-36-04](https://user-images.githubusercontent.com/2079937/90770919-ce571d00-e2f2-11ea-8b31-02352932527a.png)
![Crazy Castle 2020-08-20 14-36-38](https://user-images.githubusercontent.com/2079937/90770917-ce571d00-e2f2-11ea-9ac8-b1868ae71d83.png)
![Crazy Castle 2020-08-20 14-36-43](https://user-images.githubusercontent.com/2079937/90770915-cdbe8680-e2f2-11ea-8248-e842bf080b57.png)
![Crazy Castle 2020-08-20 14-37-11](https://user-images.githubusercontent.com/2079937/90770914-cd25f000-e2f2-11ea-9946-3495dd64ecf7.png)
![Crazy Castle 2020-08-20 14-37-15](https://user-images.githubusercontent.com/2079937/90770909-cac39600-e2f2-11ea-90d9-4b97a8e593d2.png)

And I don't know if this is a bug of 0.3.0, but I can't remove benches and bins with the clear scenery tool.

**Comment by tubbo** [comment]
Ah ok, that might have to do with the RCT data/scenario. I only have the data for RCT2 so I can't test it against RCT1 or anything, but I would imagine that if you pick the right components it will work. Unfortunately, the order these items appear in the list is non-deterministic so I'm kinda depending on the `.index` of the list of footpath additions being the same as the numerical value I have to set in order to place the bench/bin on the path. I'm not sure if I can know which benches/bins would be "correct" for RCT1.

I tried it on Amity Airfield from RCT2 and it seems to work with the space-themed ones:
<img width="1275" alt="Screen Shot 2020-08-20 at 12 25 53 PM" src="https://user-images.githubusercontent.com/113026/90798770-5b44ab00-e2e0-11ea-9b0f-3d1372f855c7.png">

**Comment by tubbo** [comment]
@nepumax I just released `v0.2.0` of this plugin which looked like it included some fixes that might have fixed things for you? It seems like non-English and some non-RCT2 scenarios suffered from bins/benches not getting built properly in their parks.

**Comment by nepumax** [comment]
It works now! Tested it on Forest Frontiers. Thanks, mate!
