### ISSUE TITLE
Queue Line error from #55 still occurring

### ISSUE THREAD

**Issue by AuGold** [tubbo/openrct2-benchwarmer#75]
It looks like while you created v1.0.2 you never published it, so the error from #55 still occurs on the most recent version that is possible to download.

**Comment by TSideScripting** [comment]
I found what fixed this in the latest version of the repo, but I am not smart enough to know how to push this to releases.
To fix it yourself, open `benchwarmer.js` with the text editor of your choice (VS Code, Notepad++, etc.) and head down to line 333. You should see the following on lines 333–337:
```js
var _b = args, x = _b.x, y = _b.y, z = _b.z, slope = _b.slope;
var addition = settings.bin;
if (args.object == 11) {
    addition = settings.queuetv;
}
```
Replace lines 333–337 with the following:
```js
var _b = args, x = _b.x, y = _b.y, z = _b.z, slope = _b.slope, constructFlags = _b.constructFlags;
var addition = settings.bin;
if (constructFlags === 1) {
    addition = settings.queuetv;
}
```
If you haven't already, follow the steps in issue https://github.com/tubbo/openrct2-benchwarmer/issues/76#issuecomment-1793735455 to stop lamp posts being placed instead of bins/benches.

**Comment by tubbo** [comment]
v1.1.0 should release properly today, some of the CI was broken so it never made it to the release stage.

**Comment by tubbo** [comment]
https://github.com/tubbo/openrct2-benchwarmer/releases/tag/v1.1.0
